7 модуль
js-tasks-ru/jsbasic-20201022_shturnova pull request #5
Opened 2020-11-25 01:47 UTC by Spinelly

2020-11-25 03:06 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Учебный проект: Пошаговый слайдер, часть 2
+ должен задавать закрашиваемую область до ползунка
+ должен добавлять класс slider_dragging
+ должен перемещать ползунок после захвата и перемещения
+ должен генерировать событие изменения значения
+ первый шаг должен быть активным
+ после создания должно быть нарисовано количество шагов переданное в момент создания
+ должен задавать ширину закрашиваемой области до ползунка
+ должен перемещать ползунок
+ должен генерировать событие изменения значения
```
```diff
Учебный проект: Пошаговый слайдер, часть 1
+ должен генерировать событие изменения значения
+ должен задавать ширину закрашиваемой области до ползунка
+ должен перемещать ползунок
+ первый шаг должен быть активным
+ после создания должно быть нарисовано количество шагов, переданное в момент создания
```
```diff
Учебный проект: Модальное окно
+ должен задавать заголовок модального окна
+ должен вставлять содержимое модального окна в элемента с классом "modal__body"
+ должна создавать основной элемент модального окна
+ должна создавать прозрачный фон
+ должна добавлять класс "is-modal-open" элементу body
+ при вызове метода close(), вёрстка модального окна должна удаляться из body
+ при клике по [X], вёрстка модального окна должна удаляться из body
+ при нажатии клавиши ESC, должен удаляться класс "is-modal-open" с элемента body
+ при нажатии клавиши ESC, вёрстка модального окна должна удаляться из body
+ при вызове метода close(), должен удаляться класс "is-modal-open" с элемента body
+ при клике по [X], должен удаляться класс "is-modal-open" с элемента body
```
```diff
Учебный проект: Лента-Меню
+ созданное событие должно содержать в себе уникальный идентификатор товара ("id")
+ после клика по ссылке, должно быть создано событие
+ при клике на кнопке "вперёд", должна прокру��ить на 350px вперёд
+ при клике по кнопке "назад", должна прокрутить на 350px назад
+ должна добавлять корневой элемент в свойство "elem"
+ должна отрисовать все категории
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-11-26 02:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Учебный проект: Модальное окно
+ должен задавать заголовок модального окна
+ должна добавлять класс "is-modal-open" элементу body
+ должна создавать прозрачный фон
+ должна создавать основной элемент модального окна
+ при клике по [X], должен удаляться класс "is-modal-open" с элемента body
+ при клике по [X], вёрстка модального окна должна удаляться из body
+ при нажатии клавиши ESC, должен удаляться класс "is-modal-open" с элемента body
+ при нажатии клавиши ESC, вёрстка модального окна должна удаляться из body
+ при вызове метода close(), вёрстка модального окна должна удаляться из body
+ при вызове метода close(), должен удаляться класс "is-modal-open" с элемента body
+ должен вставлять содержимое модального окна в элемента с классом "modal__body"
```
```diff
Учебный проект: Список товаров
- товары должны быть отфильтрованы по полю maxSpiciness
- должен объединять объекты filters между разными вызовами
- товары должны быть отфильтрованы по полю category
- товары должны быть отфильтрованы по полю vegeterianOnly
- товары должны быть отфильтрованы по полю noNuts
- после создания должны быть показаны карточки для всех товаров
```
```diff
Учебный проект: Пошаговый слайдер, часть 1
+ первый шаг должен быть активным
+ после создания должно быть нарисовано количество шагов, переданное в момент создания
+ должен генерировать событие изменения значения
+ должен задавать ширину закрашиваемой области до ползунка
+ должен перемещать ползунок
```
```diff
Учебный проект: Лента-Меню
+ должна добавлять корневой элемент в свойство "elem"
+ должна отрисовать все категории
+ после клика по ссылке, должно быт�� создано событие
+ созданное событие должно содержать в себе уникальный идентификатор товара ("id")
+ при клике по кнопке "назад", должна прокрутить на 350px назад
+ при клике на кнопке "вперёд", должна прокрутить на 350px вперёд
```
```diff
Учебный проект: Корзина, часть 1
- корзина должна быть пустой после создания
- должна измениться общая стоимость
- должно измениться общее количество товаров
- должна измениться общая стоимость
- корзина должна стать пустой
- должно уменьшаться количество единиц этого товара
- должна измениться общая стоимость
- должно увеличиваться количество единиц этого товара
- добавление товара должно обновить иконку корзины
- должно измениться общее количество товаров
- должна измениться общая стоимость
- корзина должна быть не пустой после добавления товара
```
```diff
Учебный проект: Корзина, часть 2
- должна измениться общая стоимость
- должно измениться общее количество товаров
- должно измениться общее количество товаров
- должна измениться общая стоимость
- корзина должна быть не пустой после добавления товара
- добавление товара должно обновить иконку корзины
- корзина должна быть пустой после создания
- должна отправлять заказ
- должна предотвращать перезагрузку страницы
- должна отображать текст о размещении заказа
- должна менять заголовок модальному окну
- должна удалять все товары из корзины
- должна отображать увеличение товара на единицу
- должна отображать увеличение общей стоимости товара
- должна отображать увеличение стоимости товара
- должна закрывать модальное окно если товаров в корзине не осталось
- должна отображать уменьшение общей стоимости товара
- должна удалять товар из корзины если его количество равно 0
- должна отображать уменьшение стоимости товара
- должна отображать уменьшение товара на единицу
- должна отображать карточку товара
- должна задавать заголовок модальному окну
- должна открывать модальное окно
- должна отображать форму заказа
```
```diff
Учебный проект: Пошаговый слайдер, часть 2
+ должен генерировать событие изменения значения
+ должен задавать ширину закрашиваемой области до ползунка
+ должен перемещать ползунок
+ должен добавлять класс slider_dragging
+ должен задавать закрашиваемую область до ползунка
+ должен перемещать ползунок после захвата и перемещения
+ должен генерировать событие изменения значения
+ после создания должно быть нарисовано количество шагов переданное в момент создания
+ первый шаг должен быть активным
```
```diff
Учебный проект: Иконка корзины
+ иконка корзины должна быть скрыта
+ иконка корзины должна быть видимой на странице
- иконка должна смещаться на 10px левее главного контейнера
- иконка должна быть спозиционирована фиксированно
- иконка должна быть спозиционирована фиксированно
- иконка должна смещаться на 20px правее от первого элемент в документе с классом `container`
```

2020-11-26 03:14 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Учебный проект: Корзина, часть 1
- корзина должна быть пустой после создания
- корзина должна быть не пустой после добавления товара
- добавление товара должно обновить иконку корзины
- должно измениться общее количество товаров
- должна измениться общая стоимость
- корзина должна стать пустой
- должна измениться общая стоимость
- должно уменьшаться количество единиц этого товара
- должно увеличиваться количество единиц этого товара
- должна измениться общая стоимость
- должна измениться общая стоимость
- должно измениться общее количество товаров
```
```diff
Учебный проект: Иконка корзины
+ иконка корзины должна быть скрыта
+ иконка корзины должна быть видимой на странице
- иконка должна быть спозиционирована фиксированно
- иконка должна смещаться на 10px левее главного контейнера
- иконка должна смещаться на 20px правее от первого элемент в документе с классом `container`
- иконка должна быть спозиционирована фиксированно
```
```diff
Учебный проект: Модальное окно
+ должен вставлять содержимое модального окна в элемента с классом "modal__body"
+ при вызове метода close(), должен удаляться класс "is-modal-open" с элемента body
+ при нажатии ��лавиши ESC, вёрстка модального окна должна удаляться из body
+ при клике по [X], вёрстка модального окна должна удаляться из body
+ при клике по [X], должен удаляться класс "is-modal-open" с элемента body
+ при вызове метода close(), вёрстка модального окна должна удаляться из body
+ при нажатии клавиши ESC, должен удаляться класс "is-modal-open" с элемента body
+ должна создавать основной элемент модального окна
+ должна добавлять класс "is-modal-open" элементу body
+ должна создавать прозрачный фон
+ должен задавать заголовок модального окна
```
```diff
Учебный проект: Список товаров
- товары должны быть отфильтрованы по полю category
- должен объединять объекты filters между разными вызовами
- товары должны быть отфильтрованы по полю maxSpiciness
- товары должны быть отфильтрованы по полю noNuts
- товары должны быть отфильтрованы по полю vegeterianOnly
- после создания должны быть показаны карточки для всех товаров
```
```diff
Учебный проект: Пошаговый слайдер, часть 2
+ должен перемещать ползунок
+ должен генерировать событие изменения значения
+ должен задавать ширину закрашиваемой области до ползунка
+ после создания должно быть нарисовано количество шагов переданное в момент создания
+ первый шаг должен быть активным
+ должен генерировать событие изменения значения
+ должен добавлять класс slider_dragging
+ должен перемещать ползунок после захвата и перемещения
+ должен задавать закрашиваемую область до ползунка
```
```diff
Учебный проект: Лента-Меню
+ созданное событие должно содержать в себе уникальный идентификатор товара ("id")
+ после клика по ссылке, должно быть создано событие
+ при клике на кнопке "вперёд", должна прокрутить на 350px вперёд
+ при клике по кнопке "назад", должна прокрутить на 350px назад
+ должна отрисовать все категории
+ должна добавлять корневой элемент в свойство "elem"
```
```diff
Учебный проект: Корзина, часть 2
- корзина должна быть не пустой после добавления товара
- добавление товара должно обновить иконку корзины
- корзина должна быть пустой после создания
- должна закрывать модальное окно если товаров в корзине не осталось
- должна отображать уменьшение общей стоимости товара
- должна удалять товар из корзины если его количество равно 0
- должна отображать уменьшение стоимости товара
- должна отображать уменьшение товара на единицу
- должна отображать увеличение общей стоимости товара
- должна отображать увеличение стоимости товара
- должна отображать увеличение товара на единицу
- должна предотвращать перезагрузку страницы
- должна удалять все товары из корзины
- должна отображать текст о размещении заказа
- должна менять заголовок модальному окну
- должна отправлять заказ
- должна отображать форму заказа
- должна отображать карточку товара
- должна задавать заголовок модальному окну
- должна открывать модальное окно
- должна измениться общая стоимость
- должно измениться общее количество товаров
- должно измениться общее количество товаров
- должна измениться общая стоимость
```
```diff
Учебный проект: Пошаговый слайдер, часть 1
+ после создания должно быть нарисовано количество шагов, переданное в момент создания
+ первый шаг должен быть активным
+ должен генерировать событие изменения значения
+ должен перемещать ползунок
+ должен задавать ширину закрашиваемой области до ползунка
```

2020-11-26 11:44 UTC, koalex requested changes
Убедись что `npm test` не выдаёт ошибок и тогда заново отправляй на проверку. Жду исправлений.

2020-11-26 22:53 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Учебный проект: Список товаров
- товары должны быть отфильтрованы по полю noNuts
- товары должны быть отфильтрованы по полю vegeterianOnly
- должен объединять объекты filters между разными вызовами
- товары должны быть отфильтрованы по полю maxSpiciness
- товары должны быть отфильтрованы по полю category
- после создания должны быть показаны карточки для всех товаров
```
```diff
Учебный проект: Корзина, часть 1
- должна измениться общая стоимость
- корзина должна стать пустой
- должна измениться общая стоимость
- должно уменьшаться количество единиц этого товара
- должно увеличиваться количество единиц этого товара
- должна измениться общая стоимость
- должно измениться общее количество товаров
- должна измениться общая стоимость
- должно измениться общее количество товаров
- корзина должна быть пустой после создания
- корзина должна быть не пустой после добавления товара
- добавление товара должно обновить иконку корзины
```
```diff
Учебный проект: Корзина, часть 2
- должна отображать увеличение товара на единицу
- должна отображать увеличение стоимости товара
- должна отображать увеличение общей стоимости товара
- должна удалять товар из корзины если его количество равно 0
- должна отображать уменьшение товара на единицу
- должна отображать уменьшение стоимости товара
- должна отображать уменьшение общей стоимости товара
- должна закрывать модальное окно если товаров в корзине не осталось
- должна отображать форму заказа
- должна задавать заголовок модальному окну
- должна отображать карточку товара
- должна открывать модальное окно
- должна удалять все товары из корзины
- должна менять заголовок модальному окну
- должна отображать текст о размещении заказа
- должна предотвращать перезагрузку страницы
- должна отправлять заказ
- добавление товара должно обновить ико��ку корзины
- должна измениться общая стоимость
- должно измениться общее количество товаров
- должна измениться общая стоимость
- должно измениться общее количество товаров
- корзина должна быть не пустой после добавления товара
- корзина должна быть пустой после создания
```
```diff
Учебный проект: Лента-Меню
+ после клика по ссылке, должно быть создано событие
+ созданное событие должно содержать в себе уникальный идентификатор товара ("id")
+ при клике по кнопке "назад", должна прокрутить на 350px назад
+ при клике на кнопке "вперёд", должна прокрутить на 350px вперёд
+ должна добавлять корневой элемент в свойство "elem"
+ должна отрисовать все категории
```
```diff
Учебный проект: Модальное окно
+ должна создавать основной элемент модального окна
+ должна создавать прозрачный фон
+ должна добавлять класс "is-modal-open" элементу body
+ должен задавать заголовок модального окна
+ должен вставлять содержимое модального окна в элемента с классом "modal__body"
+ при вызове метода close(), вёрстка модального окна должна удаляться из body
+ при нажатии клавиши ESC, должен удаляться класс "is-modal-open" с элемента body
+ при вызове метода close(), должен удаляться класс "is-modal-open" с элемента body
+ при нажатии клавиши ESC, вёрстка модального окна должна удаляться из body
+ при клике по [X], должен удаляться класс "is-modal-open" с элемента body
+ при клике по [X], вёрстка модального окна должна удаляться из body
```
```diff
Учебный проект: Пошаговый слайдер, часть 1
+ после создания должно быть нарисовано количество шагов, переданное в момент создания
+ первый шаг должен быть активным
+ должен задавать ширину закрашиваемой области до ползунка
+ должен генерировать событие изменения значения
+ должен перемещать ползунок
```
```diff
Учебный проект: Пошаговый слайдер, часть 2
+ должен перемещать ползунок
+ должен генерировать событие изменения значения
+ должен задавать ширину закрашиваемой области до ползунка
+ должен добавлять класс slider_dragging
+ должен задавать закрашиваемую область до ползунка
+ должен генерировать событие изменения значения
+ долж��н перемещать ползунок после захвата и перемещения
+ после создания должно быть нарисовано количество шагов переданное в момент создания
+ первый шаг должен быть активным
```
```diff
Учебный проект: Иконка корзины
+ иконка корзины должна быть скрыта
+ иконка корзины должна быть видимой на странице
- иконка должна смещаться на 10px левее главного контейнера
- иконка должна быть спозиционирована фиксированно
- иконка должна смещаться на 20px правее от первого элемент в документе с классом `container`
- иконка должна быть спозиционирована фиксированно
```

2020-11-27 14:48 UTC, koalex commented
ошибки так и не исправлены. Напиши мне в Slack если не получается.

2020-11-29 01:32 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 8-module/1-task/task.test.js — изменен
```

2020-11-29 18:21 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 8-module/1-task/task.test.js — изменен
```

2020-11-29 18:29 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 8-module/1-task/task.test.js — изменен
```

2020-11-29 18:37 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 8-module/1-task/task.test.js — изменен
```

2020-11-29 18:47 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 8-module/1-task/task.test.js — изменен
```

2020-12-02 14:18 UTC, koalex approved these changes

2020-12-02 14:20 UTC, merged